/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoriqueRouteImport } from './routes/theorique'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as ConclusionRouteImport } from './routes/conclusion'
import { Route as IndexRouteImport } from './routes/index'

const TheoriqueRoute = TheoriqueRouteImport.update({
  id: '/theorique',
  path: '/theorique',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionRoute = ConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/discussion': typeof DiscussionRoute
  '/methodologie': typeof MethodologieRoute
  '/resultats': typeof ResultatsRoute
  '/theorique': typeof TheoriqueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/discussion': typeof DiscussionRoute
  '/methodologie': typeof MethodologieRoute
  '/resultats': typeof ResultatsRoute
  '/theorique': typeof TheoriqueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/discussion': typeof DiscussionRoute
  '/methodologie': typeof MethodologieRoute
  '/resultats': typeof ResultatsRoute
  '/theorique': typeof TheoriqueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conclusion'
    | '/discussion'
    | '/methodologie'
    | '/resultats'
    | '/theorique'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conclusion'
    | '/discussion'
    | '/methodologie'
    | '/resultats'
    | '/theorique'
  id:
    | '__root__'
    | '/'
    | '/conclusion'
    | '/discussion'
    | '/methodologie'
    | '/resultats'
    | '/theorique'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConclusionRoute: typeof ConclusionRoute
  DiscussionRoute: typeof DiscussionRoute
  MethodologieRoute: typeof MethodologieRoute
  ResultatsRoute: typeof ResultatsRoute
  TheoriqueRoute: typeof TheoriqueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theorique': {
      id: '/theorique'
      path: '/theorique'
      fullPath: '/theorique'
      preLoaderRoute: typeof TheoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusion': {
      id: '/conclusion'
      path: '/conclusion'
      fullPath: '/conclusion'
      preLoaderRoute: typeof ConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConclusionRoute: ConclusionRoute,
  DiscussionRoute: DiscussionRoute,
  MethodologieRoute: MethodologieRoute,
  ResultatsRoute: ResultatsRoute,
  TheoriqueRoute: TheoriqueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
